"""Version information."""
__title__ = "voting"
__description__ = "Voting and election related functions."
__url__ = "https://github.com/crflynn/voting"
__version__ = "0.1.3"
__author__ = "Christopher Flynn"
__author_email__ = "crf204@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018-2019 Christopher Flynn"
__docs_copyright__ = "2018-2019 Christopher Flynn"
