dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install poetry==0.12.17
install:
  - env -u VIRTUAL_ENV poetry install
  - env -u VIRTUAL_ENV poetry add codecov
script:
  - env -u VIRTUAL_ENV poetry run pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then (env -u VIRTUAL_ENV poetry run black --check .); fi
after_success:
  - env -u VIRTUAL_ENV poetry run codecov
